#!/usr/bin/env python3
#
# Adapts images to a given resolution.
#
# Copyright (C) 2016 Arun Prakash Jana <engineerarun@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import sys
import os
import shutil
import PIL
from PIL import Image, ImageFile

HRES = 0
VRES = 0
scale = None
convert = False
dot = False
eraseexif = False
force = False
keep = False
nolarge = False
optimize = False
quiet = False
recursive = False
overwrite = False
debug = False
pad = '_IMGD'
no_res_opt = False
_VERSION_ = '0.1'

def getres(res):
    hxv = res.split('x')
    if len(hxv) != 2:
        return (0, 0)

    try:
        return(int(hxv[0]), int(hxv[1]))
    except:
        return (0, 0)

def traverse_dir(path):
    try:
        for entry in os.scandir(path):
            # Add check for hidden here
            if not dot and entry.name.startswith('.'):
                continue

            if entry.is_dir():
                if recursive:
                    if not os.access(entry.path, os.W_OK | os.X_OK):
                        print(entry.path + ': no permission')
                        continue
                    traverse_dir(entry.path)
            else:
                resize_image(entry.path)
    except OSError as e:
        print(e)

def resize_image(src):
    global HRES, VRES
    # TODO: add a check for image size comparison with convert
    converted = False
    name, ext = os.path.splitext(src)

    try:
        img = Image.open(src)
        srcformat = img.format

        # if 'only' convert option is specified,
        # nothing to be done for non-PNG images
        if no_res_opt and not optimize and srcformat != 'PNG':
            if debug:
                print('resize_image: cannot convert non-PNG')
            return

        try:
            if eraseexif:
                exifdata = b''
            else:
                exifdata = img.info['exif']
        except:
            exifdata = b''
    except OSError as e:
        if not str(e).startswith('cannot identify image file'):
            print(e)
        return

    hres = img.size[0]
    vres = img.size[1]
    ImageFile.MAXBLOCK = hres * vres

    if scale:
        if scale == 100:
            _hres = hres
            _vres = vres
        else:
            _hres = hres * scale/float(100)
            # use custom round()
            if _hres >= int(_hres) + .5:
                _hres = _hres + 1
            _hres = int(_hres)

            _vres = vres * scale/float(100)
            if _vres >= int(_vres) + .5:
                _vres = _vres + 1
            _vres = int(_vres)

        img = img.resize((_hres, _vres), PIL.Image.ANTIALIAS)
        if debug:
            print('resize_image: scaled to [%dx%d]' % (HRES, VRES))
    elif HRES == hres and VRES == vres:
        if debug:
            print('resize_image: same res [%dx%d]' % (HRES, VRES))
    elif force:
        img = img.resize((HRES, VRES), PIL.Image.ANTIALIAS)
        if debug:
            print('resize_image: brute force res to [%dx%d]' % (HRES, VRES))
    else:
        ratio_img = float(hres/vres)
        ratio_target = float(HRES/VRES)

        if ratio_img >= ratio_target:
            if nolarge and HRES > hres:
                return

            # re-sample as per target horizontal resolution
            hratio = HRES/float(hres)
            target_vres = vres * hratio
            if target_vres >= int(target_vres) + .5:
                target_vres = target_vres + 1
            target_vres = int(target_vres)

            img = img.resize((HRES, target_vres), PIL.Image.ANTIALIAS)
            if debug:
                print('resize_image: hres calculated %dx%d' % (HRES, target_vres))
        else:
            if nolarge and VRES > vres:
                return

            # re-sample as per target vertical resolution
            vratio = VRES/float(vres)
            target_hres = hres * vratio
            if target_hres >= int(target_hres) + .5:
                target_hres = target_hres + 1
            target_hres = int(target_hres)

            img = img.resize((target_hres, VRES), PIL.Image.ANTIALIAS)
            if debug:
                print('resize_image: vres calculated %dx%d' % (target_hres, VRES))

    if not quiet:
        stats = src + '\n%dx%d -> %dx%d' % (hres, vres, img.size[0], img.size[1])

    try:
        if not optimize:
            if convert and srcformat == 'PNG':
                img.save(name + pad + '.jpg', 'JPEG', exif=exifdata)
                converted = True
            else:
                img.save(name + pad + ext, srcformat, exif=exifdata)
        else:
            if convert and srcformat == 'PNG':
                img.save(name + pad + '.jpg', 'JPEG', optimize=True, exif=exifdata)
                converted = True
            else:
                img.save(name + pad + ext, srcformat, optimize=True, exif=exifdata)

        if not quiet:
            if convert and srcformat == 'PNG':
                print('%s\n%ld bytes -> %ld bytes\n' % (stats, os.path.getsize(src), os.path.getsize(name + pad + '.jpg')))
            else:
                print('%s\n%ld bytes -> %ld bytes\n' % (stats, os.path.getsize(src), os.path.getsize(name + pad + ext)))

        if overwrite:
            if converted:
                os.remove(src)
                shutil.move(name + pad + '.jpg', name + '.jpg')
            else:
                shutil.move(name + pad + ext, src)
    except OSError as e:
        print(e)

class ExtendedArgumentParser(argparse.ArgumentParser):
    """Extend classic argument parser"""

    # Print additional help and info
    @staticmethod
    def print_extended_help(file=None):
        if not file:
            file = sys.stderr

        file.write('''
Version %s
Copyright (C) 2016 Arun Prakash Jana <engineerarun@gmail.com>
License: GPLv3
Webpage: https://github.com/jarun/imgd
''' % _VERSION_)

    # Help
    def print_help(self, file=None):
        super(ExtendedArgumentParser, self).print_help(file)
        self.print_extended_help(file)

def parse_args(args=None, namespace=None):
    """Parse imgd arguments/options.
    Parameters
    ----------
    args : list, optional
        Arguments to parse. Default is ``sys.argv``.
    namespace : argparse.Namespace
        Namespace to write to. Default is a new namespace.
    Returns
    -------
    argparse.Namespace
        Namespace with parsed arguments / options.
    """

    argparser = ExtendedArgumentParser(description='Adapt images to a resolution.')
    addarg = argparser.add_argument
    addarg('-s', '--scale', dest='scale', type=int, metavar='%',
           help='scale image by percentage')
    addarg('-x', '--res', dest='res', nargs=1, metavar='HxV',
           help='output resolution in HxV representation')
    addarg('-c', '--convert', dest='convert', action='store_true',
           help='convert PNG to JPG format [default: off]')
    addarg('-d', '--dot', dest='dot', action='store_true',
           help='include hidden files (on Linux) [default: off]')
    addarg('-e', '--eraseexif', action='store_true',
           help='erase exif metadata [default: off]')
    addarg('-f', '--force', dest='force', action='store_true',
           help='force to exact specified resolution [default: off]')
    addarg('-k', '--keep', dest='keep', action='store_true',
           help='best fit for screen [default: off]')
    addarg('-n', '--nolarge', dest='nolarge', action='store_true',
           help='do not enlarge smaller images [default: scale up]')
    addarg('-p', '--optimize', dest='optimize', action='store_true',
           help='optimize the output images [default: off]')
    addarg('-q', '--quiet', dest='quiet', action='store_true',
           help='operate silently [default: verbose]')
    addarg('-r', '--recursive', dest='recursive', action='store_true',
           help='process directories recursively [default: off]')
    addarg('-w', '--overwrite', dest='overwrite', action='store_true',
           help='overwrite source images [default: off]')
    addarg('-z', '--debug', dest='debug', action='store_true',
           help='enable debug logs [default: off]')
    addarg('keywords', nargs='+', metavar='PATH',
           help='source file or directory')

    # Show help and exit if no arguments
    if len(sys.argv) < 2:
        argparser.print_help(sys.stderr)
        sys.exit(1)

    return argparser.parse_args(args, namespace)

def main():
    global HRES, VRES, scale, convert, dot, eraseexif, force, nolarge, \
           optimize, quiet, recursive, overwrite, debug, no_res_opt

    args = parse_args()

    if (args.res is not None and args.scale is not None):
        print('specify either resolution or scale')
        return

    if args.scale is not None:
        if (args.scale <= 0):
            print('scale should be > 0%')
            return
        if args.scale > 100 and args.nolarge:
            print('option --nolarge used, cannot scale > 100%')
            return
        scale = args.scale
    elif args.res is not None:
        HRES, VRES = getres(args.res[0])
        if HRES == 0 or VRES == 0:
            print('resolution must be numeric and > 0')
            return
    elif args.convert or args.optimize:
        no_res_opt = True
        scale = 100
    else:
        print('missing image transformation')
        return

    convert = args.convert
    dot = args.dot
    eraseexif = args.eraseexif
    force = args.force
    nolarge = args.nolarge
    optimize = args.optimize
    quiet = args.quiet
    recursive = args.recursive
    overwrite = args.overwrite
    debug = args.debug

    if len(args.keywords) == 0:
        print('no source specified')
        return

    for path in args.keywords:
        if not os.path.exists(path):
            print('%s does not exist' % path)
        elif os.path.isdir(path):
            traverse_dir(path)
        else:
            resize_image(path)

if __name__ == '__main__':
    main()
