.TH "IMGD" "1" "Aug 2016" "Version 0.1" "User Commands"
.SH NAME
imgd \- Resize or rotate JPEG and PNG images
.SH SYNOPSIS
.B imgd [OPTIONS] PATH [PATH ...]
.SH DESCRIPTION
.B imgd
(read \fIimaged\fR) is a multiprocessing command line image resizer and rotator for JPEG and PNG images.
.PP
Features:
  * resize by percentage or resolution
  * rotate by specified angle
  * adaptive resize considering orientation
  * brute force to a resolution
  * optimize images to save more space
  * convert PNG to JPEG
  * erase exif metadata
  * force only larger to smaller resize
  * process directories recursively
  * overwrite source image option
.PP
Output image names are appended with \fB_IMGD\fR if overwrite option is not used. By default \fB_IMGD\fR files are not processed. Doing so may lead to potential race conditions when overwrite option is used.
.PP
.B Adaptive mode
.PP
  - If the specified and image orientations are same [(H >= V and h > v) or (H < V and h < v)], the image is resized with the longer specified side as reference.
  - In case of cross orientation [(H >= V and h <= v) or (H < V and h >= v)], the image is resized with the shorter specified side as reference. Same as non-adaptive.
.PP
  For example, if an image has a resolution of 2048x1365 and is being resized to 1366x768:
.PP
  - In regular mode (default), output image resolution will be 1152x768
  - In adaptive mode, output image resolution will be 1366x910
.SH OPTIONS
.TP
.BI "-h, --help"
Show help text and exit.
.TP
.BI "-s, --scale=" %
Scale image by percentage.
.TP
.BI "-x, --res=" HxV
Output resolution in HRESxVRES representation.
.TP
.BI "-o, --rotate=" deg
Rotate by specified angle.
.TP
.BI "-a, --adapt"
Adapt to specified resolution considering the orientation of the image. Disabled by default.
.TP
.BI "-c, --convert"
Convert PNG images to JPEG to save on space. The output image is saved with '.jpg' extension.
.TP
.BI "-d, --dot"
Include hidden files (Linux-specific). By default hidden files are skipped on Linux.
.TP
.BI "-e, --eraseexif"
Erase EXIF metadata of JPEG images. Preserved by default.
.TP
.B "-f, --force"
Force to the exact specified resolution. Disabled by default.
.TP
.B "-n, --enlarge"
Enlarge smaller images. By default smaller images are not scaled if specified resolution is greater.
.TP
.BI "-p, --optimize"
Optimize output images using PIL library optimization algorithm. Disabled by default.
.TP
.BI "-q, --quiet"
Do not show any operational output.
.TP
.B "-r, --recursive"
Recursively process sub-directories. By default only the specified directory is processed.
.TP
.BI "-w, --overwrite"
Overwrite the source images. By default an output image is saved with \fB_IMGD\fR appended to the source image name.
.br
.B NOTE:
If overwrite and convert options are used together, source PNG images are deleted.
.TP
.BI "-z, --debug"
Enable debugging.
.SH EXAMPLES
.PP
.IP 1. 4
Convert some images and directories:
.PP
.EX
.IP
.B $ imgd -x 1366x768 ~/ ~/Pictures/image3.png ~/Downloads/
/home/testuser/image1.png
3840x2160 -> 1365x768
11104999 bytes -> 1486426 bytes

/home/testuser/image2.jpg
2048x1365 -> 1152x768
224642 bytes -> 31421 bytes

/home/testuser/Pictures/image3.png
1920x1080 -> 1365x768
2811155 bytes -> 1657474 bytes

/home/testuser/Downloads/image4
2048x1365 -> 1152x768
224642 bytes -> 31421 bytes
.EE
.PP
.IP 2. 4
Scale an image by 75% and overwrite the source image:
.PP
.EX
.IP
.B $ imgd -s 75 -w ~/image.jpg
/home/testuser/image.jpg
1366x767 -> 1025x575
120968 bytes -> 45040 bytes
.EE
.PP
.IP 3. 4
Rotate an image by 90 degree:
.PP
.EX
.IP
.B $ imgd -o 90 ~/image.jpg
120968 bytes -> 72038 bytes
.EE
.PP
.IP 4. 4
Adapt the images in the current directory to 1366x1000 resolution.
.br
Convert PNG images to JPEG, visit all directories recursively and overwrite source images.
.PP
.EX
.IP
.B $ imgd -x 1366x1000 -acrw .
.EE
.SH AUTHORS
Arun Prakash Jana <engineerarun@gmail.com>
.SH HOME
.I https://github.com/jarun/imgd
.SH REPORTING BUGS
.I https://github.com/jarun/imgd/issues
.SH LICENSE
Copyright \(co 2016 Arun Prakash Jana <engineerarun@gmail.com>
.PP
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
